"""primeira migrate

Revision ID: 625f42d0dfce
Revises: 
Create Date: 2025-06-12 21:19:02.597212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625f42d0dfce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('assunto', sa.String(length=200), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contato')
    # ### end Alembic commands ###
